apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: default
  annotations:
    gateway.io/upstream: "search-service"
    gateway.io/port: "8081"
    gateway.io/weight: "1"
spec:
  selector:
    app: search
  ports:
    - port: 8081
      targetPort: 8081